-- Hidden Beyond Bot2 durable fixed-source registry.
-- Runtime discovery may use only verified locators for the five approved sources.
create table if not exists public.hidden_beyond_source_locators (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.sources(id) on delete cascade,
  locator_type text not null check (locator_type in ('channel_id','uploads_playlist_id','seed_video_id')),
  locator_value text not null,
  verified boolean not null default false,
  provenance text not null default 'unknown',
  verified_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_id, locator_type, locator_value)
);

create table if not exists public.hidden_beyond_source_health (
  source_id bigint primary key references public.sources(id) on delete cascade,
  status text not null default 'unknown' check (status in ('unknown','healthy','degraded','unavailable')),
  resolved_channel_id text,
  uploads_playlist_id text,
  last_checked_at timestamptz,
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0),
  reason text,
  diagnostics jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.hidden_beyond_source_locators enable row level security;
alter table public.hidden_beyond_source_health enable row level security;
revoke all on public.hidden_beyond_source_locators from anon, authenticated;
revoke all on public.hidden_beyond_source_health from anon, authenticated;

alter table public.source_items
  add column if not exists source_channel_id text,
  add column if not exists source_published_at timestamptz,
  add column if not exists discovery_method text;

create index if not exists source_items_series_episode_idx
  on public.source_items(source_id, series_id, episode_number)
  where active = true;
create index if not exists hidden_beyond_source_locators_lookup_idx
  on public.hidden_beyond_source_locators(source_id, active, verified, locator_type);
create index if not exists hidden_beyond_source_health_status_idx
  on public.hidden_beyond_source_health(status, updated_at);

insert into public.hidden_beyond_source_health(source_id,status,updated_at)
select id,'unknown',now() from public.sources where id in (29,30,31,32,33)
on conflict (source_id) do nothing;

insert into public.hidden_beyond_source_locators
(source_id,locator_type,locator_value,verified,provenance,verified_at,active,updated_at)
select id,'channel_id',substring(channel_url from '/channel/([^/?#]+)'),
       true,'fixed_source_config',coalesce(approval_checked_at,now()),true,now()
from public.sources
where id in (29,30,31,32,33) and channel_url ~ '/channel/[^/?#]+'
on conflict (source_id,locator_type,locator_value)
do update set verified=excluded.verified, provenance=excluded.provenance,
              verified_at=coalesce(public.hidden_beyond_source_locators.verified_at,excluded.verified_at),
              active=true, updated_at=now();

insert into public.hidden_beyond_source_locators
(source_id,locator_type,locator_value,verified,provenance,verified_at,active,updated_at)
values
(29,'seed_video_id','LESUDwiHlU4',true,'manual_same_channel_web_verification_2026-09-24',now(),true,now())
on conflict (source_id,locator_type,locator_value)
do update set verified=true, provenance=excluded.provenance, verified_at=excluded.verified_at,
              active=true, updated_at=now();
